/**
 * APIMATIC CalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { OperationType, operationTypeSchema } from '../models/operationType.js';
import { number } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class SimpleCalculatorApi extends BaseApi {
  /**
   * Calculates the expression using the specified operation.
   *
   * @param operation The operator to apply on the variables
   * @param x         The LHS value
   * @param y         The RHS value
   * @return Response from the API call
   */
  async calculate(
    operation: OperationType,
    x: number,
    y: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<number>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      operation: [operation, operationTypeSchema],
      x: [x, number()],
      y: [y, number()],
    });
    req.query('x', mapped.x);
    req.query('y', mapped.y);
    req.appendTemplatePath`/${mapped.operation}`;
    return req.callAsJson(number(), requestOptions);
  }
}
