/**
 * APIMATIC CalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OperationType
 */
export enum OperationType {
  Sum = 'SUM',
  Subtract = 'SUBTRACT',
  Multiply = 'MULTIPLY',
  Divide = 'DIVIDE',
}

/**
 * Schema for OperationType
 */
export const operationTypeSchema: Schema<OperationType> = stringEnum(
  OperationType
);
